name: Get Citation Data

on: 
 page_build: 
 schedule:
  - cron:  '0 17 * * 1,4,0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Reqs
      run: |
        sudo apt-get install python3-setuptools
    - name: Run
      run: |
        cd ./google_scholar_crawler
        pip3 install -r requirements.txt
        python3 main.py
        if [ -d "./results" ]; then
          # Copy results to main branch google-scholar-stats directory
          mkdir -p ../google-scholar-stats
          cp ./results/*.json ../google-scholar-stats/
          
          # Configure git for main branch
          cd ..
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          
          # Add and commit changes to main branch
          git add google-scholar-stats/*.json
          git commit -m "Update Google Scholar citation data [skip ci]"
          git push origin HEAD:main
        else
          echo "results directory does not exist, skipping commit and push"
        fi
      env: 
        GOOGLE_SCHOLAR_ID: TJtQW8gAAAAJ